apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test-app-system
  description: A simple test application system
spec:
  owner: user:guest
  domain: test-domain

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-app-frontend
  description: The frontend service for the test application
  annotations:
    github.com/project-slug: your-github-org/your-repo-name # Optional: Replace with your actual repo slug
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: test-app-system
  providesApis: []
  consumesApis:
    - test-app-backend-api # Assuming the backend exposes an API defined elsewhere

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-app-backend
  description: The backend service for the test application
  annotations:
    github.com/project-slug: your-github-org/your-repo-name # Optional: Replace with your actual repo slug
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: test-app-system
  providesApis:
    - test-app-backend-api # Assuming this backend provides an API
  consumesApis: []

# Optional: Define the API provided by the backend
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-app-backend-api
  description: API for the test application backend
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  system: test-app-system
  definition:
    $text: ./backend/openapi.yaml # Path to your OpenAPI spec file 